server:
  port: 18080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tea_mall?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root

#mybatis:
#  mapper-locations: classpath:mappers/**/*.xml
#告诉mybatis-plus mapper的地址
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml