server:
  port: 17070

## 告诉mybatis mapper的地址
#mybatis:
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tedu_tea_mall
    username: root
    password: root
  redis:
    host: localhost
    port: 6379

logging:
  level:
    cn.tedu: debug
